FRequest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from account.forms import CustomPasswordResetForm,CustomSetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main.urls")),
    path("account/",include("account.urls")),
    path(
        "password_reset_view/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset.html",
            form_class=CustomPasswordResetForm),
        name="password_reset"),

    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"),
        name="password_reset_done"),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            form_class=CustomSetPasswordForm),
        name="password_reset_confirm"),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"),
        name="password_reset_complete")

]

account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
        path("signup/",views.signup,name="signup"),
        path("",auth_views.LoginView.as_view(template_name="signin.html"),name="login"),
        path("logout/",auth_views.LogoutView.as_view(),name="logout"),
        ]

main/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
from django.conf import settings 
from django.conf.urls.static import static

app_name = "main"

urlpatterns = [
        path("",views.home,name="home"),
        path("add_friend/<uuid:user_id>/",views.frequest,name="request"),
        path("added/<uuid:user_id>/",views.added,name="added"),
        path("accept/<uuid:request_id>/",views.acceptrequest,name="accept"),
        path("delete/<uuid:request_id>/",views.rejectrequest,name="reject"),
        path("request/",views.allrequest,name="allrequest"),
        path("friendslist/",views.friendslist,name="friendslist"),
        path("notifications/",views.notifications,name="notifications"),
        ] + static(settings.MEDIA_URL,
                   document_root=settings.MEDIA_ROOT)

templates/accept.html
{% extends "base.html" %}
{% block title %} Request Page {% endblock %}

{% block content %}
  <header>
    <nav class="nav-links">
	    <h3>Welcome {{request.user.username}}</h2>
	    <a href="{% url 'account:logout' %}"><button>logout</button></a>
    </nav>
    <div class="f-con">
	    <a href="{% url 'main:home'%}"><h3>suggestions</h3></a>               <a href="{% url 'main:allrequest'%}"><h3>friend request</h3></a>      <a href="{% url 'main:friendslist'%}"><h3>firends({{friends.count}})</h3></a>
      <a href="{% url 'main:notifications'%}"><h3>notifications</h3></a>
    </div>
  </header>
  <hr>
  <main>
    {% for friendrequest in friendrequests %}
    <div class="suggest">
      <img src="{{ friendrequest.receiver.image.images.url }}" alt="user image">
      <h4>{{ friendrequest.sender.username}}</h4>
      <a href="{% url 'main:accept' friendrequest.pk %}"><button>accept</button>
      <a href="{% url 'main:reject' friendrequest.pk %}"><button style="background:red">reject</button></a>
    </div>
    {% endfor %}
   
  </main>
{% endblock %}

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title%} {%endblock%}</title>
  <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
    {%block content%}

    {%endblock%}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
    </script>
    <script src="{% static 'js/ajax.js' %}"></script>
</body>
</html>

templates/friendslist.html
{% extends "base.html" %}

{% block title %} Friends List {% endblock %}

{% block content %}
<header>
    <nav class="nav-links">
	    <h3>Welcome {{request.user.get_username}}</h2>
	    <a href="{% url 'account:logout' %}"><button>logout</button></a>
    </nav>
    <div class="f-con">
      <a href="{% url 'main:home'%}"><h3>suggestions</h3></a>
      <a href="{% url 'main:allrequest'%}"><h3>friend request</h3></a>
      <a href="{% url 'main:friendslist'%}"><h3>firends({{friendsnumber.count}})</h3></a>
      <a href="{% url 'main:notifications'%}"><h3>notifications</h3></a>
    </div>
  </header>
  <hr>
  <main>
   {% for friend in friends %}
    <div class="suggest">
	    <img src="{{ friend.image.images.url }}" alt="user image">
      <h4>{{friend.get_username}}</h4>
      <p>{{friend.get_contact}}</p>
    </div>
  </main>
  {% endfor %}

{%endblock%}

templates/home.html
{% extends "base.html" %} 
{% block title%} Home Page {% endblock %} 
{% block content %}

<header>
  <nav class="nav-links">
    <h3>Welcome {{request.user.get_full_name}}</h3>
    <a href="{% url 'account:logout' %}"><button>logout</button></a>
  </nav>
  <div class="f-con">
    <a href="{% url 'main:home'%}"><h3>suggestions</h3></a>
    <a href="{% url 'main:allrequest'%}"><h3>friend request</h3></a>
    <a href="{% url 'main:friendslist'%}"
      ><h3>firends({{friends.count}})</h3></a
    >
    <a href="{% url 'main:notifications'%}"><h3>notifications</h3></a>
  </div>
</header>
<hr />
<main>
  {%for suggest in suggestions%} 
  {% if suggest.username in frequestusername %}
  <div class="suggest">
    <img src="{{ suggest.image.images.url }}" alt="user image" />
    <h4>{{suggest.get_username}}</h4>
    <a href="{%url 'main:added' suggest.pk %}"
      ><button>cancel request</button></a
    >
  </div>

  {% elif suggest not in friends%}
  <div class="suggest">
    <input type="hidden" value="{{suggest.id}}" name="user-id">
    <img src="{{ suggest.image.images.url }}" alt="user image" />
    <h4>{{suggest.get_username}}</h4>
    <a href="{% url 'main:request' suggest.pk %}"
       ><button id="add" data-id="{{suggest.id}}">add friend</button></a
    >
  </div>
  {% endif %} 
  {%endfor%}
</main>

{% endblock %}

templates/notification.html
{% extends "base.html" %}

{% block title %} Notifications {% endblock %}

{% block content %}

  <header>
    <nav class="nav-links">
      <h3>Welcome {{ request.user.get_username }}</h2>
      <a href="{% url 'account:logout' %}"><button>logout</button></a>
    </nav>
    <div class="f-con">
	    <a href="{% url 'main:home'%}"><h3>suggestions</h3></a>               <a href="{% url 'main:allrequest'%}"><h3>friend request</h3></a>      <a href="{% url 'main:friendslist'%}"><h3>firends({{friends.count}})</h3></a>
	    <a href="{% url 'main:notifications'%}"><h3>notifications</h3></a>
    </div>
  </header>
  <hr>
  <main>
    {% for notification in notifications %}
    <div class="suggest">
      <img src="{{ notification.owner.image.images.url }}" alt="user image">
      <h4>{{ notification.message }}</h4>
      <br>
      <p>{{ notification.date | date:"D d M y g : i" }}</p>
    </div>
    {% endfor %}
  </main>

{% endblock %}

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <header>
    <h3 class="p-3 text-center">reset password</h3>
  </header>
  <main>
    <form method="post">
      {%csrf_token%}
      {{form.email}}
      <input type="submit" class="btn btn-primary m-2 float-end">
    </form>
  </main>
</body>
</html>

templates/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <header>
    <h3>reset password</h3>
  </header>
  <main>
    <p>your password has being changes successfully </p>
    <p>proceed to login <a href="{% url 'account:login'%}">log in</a></p>
  </main>
</body>
</html>

templates/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <header>
    <h3 class="p-3 text-center">reset password</h3>
  </header>
  <main>
    <form method=post>
      {%csrf_token%}
      {{form.newpassword1}}
      {{form.newpassword2}}
      <button class="btn btn-primary m-2 ">reset</button>
    </form>
  </main>
</body>
</html>

templates/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <header>
    <h3>reset password</h3>
  </header>
  <main>
    <p>A password has been sent to ur gmail account check and continue ur registration from there </p>
  </main>
</body>
</html>

templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">                                                <meta name="viewport" content="width=device-width, initial-scale=1
.0">                                                                      <meta http-equiv="X-UA-Compatible" content="ie=edge">                 <title>{% block title %} {% endblock %}</title>
    <style>
        * {                                                                       margin: 0;
            padding: 0;
            box-sizing: border-box;                                               font-family: Helvetica;                                           }                                                                     body {                                                                    display: flex;
            justify-content: center;                                              align-items: center;
            height: 100vh;
        }                                                                     .container {
            box-shadow: hsl(0,0%,80%) 0 0 10px;
            width: 80%;                                                           margin: 2em auto;                                                     padding: 1em;                                                     }                                                                     .container form input {                                                   width: 100%;
            padding: 10px;                                                    }
        .title {
            font-weight: 500;                                                     font-size: 1.5rem;
            margin-bottom: 1em;                                               }                                                                     form label {                                                              font-size: 1.1rem;
            font-weight: 300;
            display: inline-block;                                                margin: 8px 0;
        }
	    form label span {                                                         color: red;                                                       }
        .signup-btn {
            padding: 12px 50px;                                                   background: #27282c;
            display: inline-block;
            margin-top: 1em;                                                      color: #fff;                                                          border: 2px solid orange;                                             border-radius: 50px;                                              }
        .b {                                                                      font-size: 0.8rem;
        }
        a {                                                                       text-decoration: none;
            color: blue;
        }                                                                     .form-footer {                                                            margin-top: 0.5em;                                                    margin-bottom: 1em;
            text-align: center;                                               }
        .error-msg {                                                              color: red;                                                           margin-bottom: 0.5em;
            font-size: 0.8rem;                                                }
.error-texts {
        font-size: 0.9rem;
        color: red;
        margin-bottom: 1.5em;
        }
        .error-texts ul {                                                     margin-left: 1.5em;
        text-align: left;                                                     }                                                                     #eye {
        position: absolute;
        top: 0;                                                               right: 10px;
        top: calc(50% - 9px);
        color: #000;                                                          }                                                                     #auth-form input {                                                    width: 100%;                                                          margin: 0.5em 0;
        padding: 12px;                                                        }
    </style>
</head>                                                               <body>
        <div class="container">
        {% block content %}                                                                                                                         {% endblock %}                                                        </div>                                                        </body>                                                               </html>

templates/signin.html
{% extends "root.html" %}
{% block title %} Sign In {% endblock %}                              
{% block content %}                                                   
        <legend class="title">Sign In</legend>
         {% for message in messages %}                                                <div class="error-msg">{{ message }}</div>
        {% endfor %}
        <form action="" method="post">                                        {% csrf_token %}
		<input type="text" name="username" placeholder="Username" required>
		<br>
		<br>
		<input type="password" name="password" placeholder="Password" required>
            <button class="signup-btn">Sign In</button>                           <div class="form-footer">                                                 <span class="b">Don't have an account?</span>                         <a class="b" href="{% url 'account:signup' %}">Sign Up</a>
		    <p>forgotten password? <a href="{% url 'password_reset'%}">reset</a></p>
            </div>                                                            </form>
                                                                       {% endblock %}

templates/signup.html
{% extends "root.html" %}                                             {% block title %} Sign Up {% endblock %}

{% block content %}                                                   
        <legend class="title">Sign Up</legend>
        {% for message in messages %}                                                 <div class="error-msg">{{ message }}</div>                    {% endfor %}
                                                                              <div class="error-texts">                                             {% if form.errors %}
          {% for error in form.errors.values %}                                   {{ error }}                                                         {% endfor %}
        {% endif %}
      </div>                                                          
            <form id="auth-form" method="post">                             {% csrf_token %}
            {{ form.email }}                                                      <br>
            {{ form.username }}
            <br>
	    <div class="password-field">
                {{ form.password1 }}
                <i class="bi bi-eye-slash" id="eye"></i>                          </div>
            <div class="password-field">
                {{ form.password2 }}
                <i class="bi bi-eye-slash" id="eye"></i>
            </div>
            <button class="signup-btn">Sign Up</button>
            <div class="form-footer">                                                 <span class="b">Already have an account?</span>
                <a class="b" href="{% url 'account:login' %}">Sign In</a>                </div>
	    </form>
                                                                      {% endblock %}